services:
  - type: web
    name: caapp
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: caapp.settings
      - key: DATABASE_URL
        fromDatabase:
          name: caapp_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false

databases:
  - name: caapp_db
    plan: free
    databaseName: caapp
    user: caapp_user